version: '3'
services:
    p1-nginx:
        container_name: p1-nginx-latest
        image: p1hub/admin.protocol.one-nginx:latest
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./updaterfiles:/app/public/update"
        networks: 
          - p1devnet
        ports:
            - "8080:80"
        restart: always
