version: '3'
services:
    p1-updater-nginx:
        container_name: p1-updater-nginx
        image: nginx:1.15.4
        networks: 
          - p1devnet
        ports:
            - "8080:80"
        restart: always
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./data/:/app/public/"
        depends_on:
            - "p1-admin-php"

networks:
  p1devnet:
    external: true