version: '3'
services:
    p1-nginx-updater:
        container_name: p1-nginx-updater
        image: nginx:1.15.4
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./updaterfiles:/app/public/update"
        networks: 
          - p1devnet
        ports:
            - "8080:80"
        restart: unless-stopped
    p1-ftp-updater:
        container_name: p1-ftp-updater
        image: stilliard/pure-ftpd:hardened
        privileged: true
        restart: unless-stopped
        ports:
          - "21:21"
          - "30000-30009:30000-30009"
        networks: 
          - p1devnet
        volumes:
            - "./updaterfiles:/home/ftpuser"
            #- "./etc/pure-ftpd:/etc/pure-ftpd"
        environment:
            - PUBLICHOST=127.0.0.1
            - FTP_USER_NAME=ftpuser
            - FTP_USER_PASS=ftppass
            - FTP_USER_HOME=/home/ftpuser

networks:
  p1devnet:
    external: true