version: '3'
services:
    p1-nginx:
        container_name: p1-nginx-build
        image: nginx:1.15.4
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "../admin.protocol.one/public/:/app/public/"
            - "./updaterfiles:/app/public/update"
        networks: 
          - p1devnet
        ports:
            - "8080:80"
        restart: unless-stopped

    p1-ftp-updater:
        container_name: p1-ftp-updater
        image: stilliard/pure-ftpd:hardened
        privileged: true
        ports:
          - "21:21"
          - "30000-30009:30000-30009"
        networks: 
          - p1devnet
        volumes:
            - "./updaterfiles:/home/ftpuser"
            #- "./etc/pure-ftpd:/etc/pure-ftpd"
        environment:
            - PUBLICHOST=127.0.0.1
            - FTP_USER_NAME=ftpuser
            - FTP_USER_PASS=ftppass
            - FTP_USER_HOME=/home/ftpuser

    p1-admin-php:
        build:
          context: ../admin.protocol.one
          dockerfile: Dockerfile
        container_name: p1-admin-php-build
        env_file:
          - ./etc/.env
        networks: 
          - p1devnet
        restart: unless-stopped

    p1-api-php:
        build:
          context: ../api.protocol.one
          dockerfile: Dockerfile
        container_name: p1-api-php-build
        env_file:
          - ./etc/.env
        networks: 
          - p1devnet
        restart: unless-stopped

    p1-auth-php:
        build:
          context: ../auth.protocol.one
          dockerfile: Dockerfile
        container_name: p1-auth-php-build
        networks: 
          - p1devnet
        restart: unless-stopped

    p1-admin-mongo:        
        image: mongo:4.1.3
        container_name: p1-admin-mongo-build
        networks: 
          p1devnet:
            aliases: 
              - p1-api-mongo
        restart: unless-stopped
        volumes:
            - p1-admin-mongo:/data/db
        ports:
            - "10017:27017"

    p1-auth-mongo:
        image: mongo:4.1.3
        container_name: p1-auth-mongo-build
        restart: unless-stopped
        networks: 
          - p1devnet
        volumes:
            - p1-auth-mongo:/data/db
        ports:
            - "10018:27017"

    p1-auth-redis:
        container_name: p1-auth-redis-build
        image: redis:3.2
        networks: 
          - p1devnet
        ports:
            - "8004:6379"

volumes:
  p1-auth-mongo:
    external: true
  p1-admin-mongo:
    external: true

networks:
  p1devnet:
    external: true