version: '3'
services:
    p1-nginx:
        container_name: p1-nginx
        image: p1hub/admin.protocol.one-nginx:latest
        volumes:
            - "./configs/nginx/default.conf:/etc/nginx/conf.d/default.conf"
        networks: 
          - p1devnet
        ports:
            - "8080:80"
        restart: always

    p1-admin-php:
        image: p1hub/admin.protocol.one:latest
        container_name: p1-admin-php
        env_file:
          - ./etc/.env
        networks: 
          - p1devnet
        restart: always

    p1-api-php:
        image: p1hub/api.protocol.one:latest
        container_name: p1-api-php
        env_file:
          - ./etc/.env
        networks: 
          - p1devnet
        restart: always

    p1-auth-php:
        image: p1hub/auth.protocol.one:latest
        container_name: p1-auth-php
        networks: 
          - p1devnet
        restart: always

    p1-admin-mongo:        
        image: mongo:4.1.3
        container_name: p1-admin-mongo
        networks: 
          p1devnet:
            aliases: 
              - p1-api-mongo
        restart: always
        volumes:
            - p1-admin-mongo:/data/db
        ports:
            - "10017:27017"

    p1-auth-mongo:
        image: mongo:4.1.3
        container_name: p1-auth-mongo
        restart: always
        networks: 
          - p1devnet
        volumes:
            - p1-auth-mongo:/data/db
        ports:
            - "10018:27017"

    p1-auth-redis:
        container_name: p1-auth-redis
        image: redis:3.2
        networks: 
          - p1devnet
        ports:
            - "8004:6379"

volumes:
  p1-auth-mongo:
    external: true
  p1-admin-mongo:
    external: true

networks:
  p1devnet:
    external: true