version: '3'
services:
    p1-nginx-updater:
        container_name: p1-nginx-updater
        image: nginx:1.15.4
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./updaterfiles:/app/public/update"
        networks: 
          - p1devnet
        ports:
            - "8080:80"
        restart: always

networks:
  p1devnet:
    external: true